# Timezone to country mapping for geolocation approximation

TZ_COUNTRY_MAP = {
    "Africa/Abidjan": "Ivory Coast",
    "Africa/Accra": "Ghana",
    "Africa/Addis_Ababa": "Ethiopia",
    "Africa/Algiers": "Algeria",
    "Africa/Cairo": "Egypt",
    "Africa/Casablanca": "Morocco",
    "Africa/Johannesburg": "South Africa",
    "Africa/Lagos": "Nigeria",
    "Africa/Nairobi": "Kenya",
    "Africa/Tunis": "Tunisia",
    "America/Anchorage": "United States",
    "America/Argentina/Buenos_Aires": "Argentina",
    "America/Bogota": "Colombia",
    "America/Buenos_Aires": "Argentina",
    "America/Caracas": "Venezuela",
    "America/Chicago": "United States",
    "America/Denver": "United States",
    "America/Detroit": "United States",
    "America/Edmonton": "Canada",
    "America/Halifax": "Canada",
    "America/Havana": "Cuba",
    "America/Lima": "Peru",
    "America/Los_Angeles": "United States",
    "America/Mexico_City": "Mexico",
    "America/Montreal": "Canada",
    "America/New_York": "United States",
    "America/Panama": "Panama",
    "America/Phoenix": "United States",
    "America/Santiago": "Chile",
    "America/Sao_Paulo": "Brazil",
    "America/Toronto": "Canada",
    "America/Vancouver": "Canada",
    "Asia/Almaty": "Kazakhstan",
    "Asia/Amman": "Jordan",
    "Asia/Baghdad": "Iraq",
    "Asia/Baku": "Azerbaijan",
    "Asia/Bangkok": "Thailand",
    "Asia/Beirut": "Lebanon",
    "Asia/Bishkek": "Kyrgyzstan",
    "Asia/Colombo": "Sri Lanka",
    "Asia/Damascus": "Syria",
    "Asia/Dhaka": "Bangladesh",
    "Asia/Dubai": "United Arab Emirates",
    "Asia/Ho_Chi_Minh": "Vietnam",
    "Asia/Hong_Kong": "Hong Kong",
    "Asia/Irkutsk": "Russia",
    "Asia/Istanbul": "Turkey",
    "Asia/Jakarta": "Indonesia",
    "Asia/Jerusalem": "Israel",
    "Asia/Kabul": "Afghanistan",
    "Asia/Karachi": "Pakistan",
    "Asia/Kathmandu": "Nepal",
    "Asia/Kolkata": "India",
    "Asia/Krasnoyarsk": "Russia",
    "Asia/Kuala_Lumpur": "Malaysia",
    "Asia/Kuwait": "Kuwait",
    "Asia/Magadan": "Russia",
    "Asia/Manila": "Philippines",
    "Asia/Muscat": "Oman",
    "Asia/Nicosia": "Cyprus",
    "Asia/Novosibirsk": "Russia",
    "Asia/Qatar": "Qatar",
    "Asia/Riyadh": "Saudi Arabia",
    "Asia/Seoul": "South Korea",
    "Asia/Shanghai": "China",
    "Asia/Singapore": "Singapore",
    "Asia/Taipei": "Taiwan",
    "Asia/Tashkent": "Uzbekistan",
    "Asia/Tbilisi": "Georgia",
    "Asia/Tehran": "Iran",
    "Asia/Tokyo": "Japan",
    "Asia/Vladivostok": "Russia",
    "Asia/Yakutsk": "Russia",
    "Asia/Yekaterinburg": "Russia",
    "Asia/Yerevan": "Armenia",
    "Atlantic/Reykjavik": "Iceland",
    "Australia/Adelaide": "Australia",
    "Australia/Brisbane": "Australia",
    "Australia/Darwin": "Australia",
    "Australia/Hobart": "Australia",
    "Australia/Melbourne": "Australia",
    "Australia/Perth": "Australia",
    "Australia/Sydney": "Australia",
    "Europe/Amsterdam": "Netherlands",
    "Europe/Athens": "Greece",
    "Europe/Belgrade": "Serbia",
    "Europe/Berlin": "Germany",
    "Europe/Bratislava": "Slovakia",
    "Europe/Brussels": "Belgium",
    "Europe/Bucharest": "Romania",
    "Europe/Budapest": "Hungary",
    "Europe/Chisinau": "Moldova",
    "Europe/Copenhagen": "Denmark",
    "Europe/Dublin": "Ireland",
    "Europe/Helsinki": "Finland",
    "Europe/Istanbul": "Turkey",
    "Europe/Kiev": "Ukraine",
    "Europe/Kyiv": "Ukraine",
    "Europe/Lisbon": "Portugal",
    "Europe/Ljubljana": "Slovenia",
    "Europe/London": "United Kingdom",
    "Europe/Luxembourg": "Luxembourg",
    "Europe/Madrid": "Spain",
    "Europe/Minsk": "Belarus",
    "Europe/Monaco": "Monaco",
    "Europe/Moscow": "Russia",
    "Europe/Oslo": "Norway",
    "Europe/Paris": "France",
    "Europe/Prague": "Czech Republic",
    "Europe/Riga": "Latvia",
    "Europe/Rome": "Italy",
    "Europe/Samara": "Russia",
    "Europe/Sarajevo": "Bosnia and Herzegovina",
    "Europe/Skopje": "North Macedonia",
    "Europe/Sofia": "Bulgaria",
    "Europe/Stockholm": "Sweden",
    "Europe/Tallinn": "Estonia",
    "Europe/Tirane": "Albania",
    "Europe/Vienna": "Austria",
    "Europe/Vilnius": "Lithuania",
    "Europe/Warsaw": "Poland",
    "Europe/Zagreb": "Croatia",
    "Europe/Zurich": "Switzerland",
    "Indian/Maldives": "Maldives",
    "Indian/Mauritius": "Mauritius",
    "Pacific/Auckland": "New Zealand",
    "Pacific/Fiji": "Fiji",
    "Pacific/Guam": "Guam",
    "Pacific/Honolulu": "United States",
    "Pacific/Noumea": "New Caledonia",
    "Pacific/Tahiti": "French Polynesia",
}


def get_country_by_timezone(timezone: str) -> str | None:
    """Get country name by timezone string."""
    return TZ_COUNTRY_MAP.get(timezone)
