name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Redeploy Portainer Stack
        uses: wirgen/portainer-stack-redeploy-action@v1.1
        with:
          portainerUrl: ${{ secrets.PORTAINER_URL }}
          accessToken: ${{ secrets.PORTAINER_TOKEN }}
          stackId: ${{ secrets.PORTAINER_STACK_ID }}
          endpointId: ${{ secrets.PORTAINER_ENDPOINT_ID }}
